/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@lendora/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildApplicationsDomainModule,
  buildAuditsDomainModule,
  buildEarlyWarningsDomainModule,
  buildIdentityDomainModule,
  buildModelsDomainModule,
  buildPoliciesDomainModule,
  buildReferralsDomainModule,
} from "../domains/index.js";
import type {
  ApplicationsDomainModule,
  AuditsDomainModule,
  EarlyWarningsDomainModule,
  IdentityDomainModule,
  ModelsDomainModule,
  PoliciesDomainModule,
  ReferralsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private applicationsModule: ApplicationsDomainModule | null = null;
  private auditsModule: AuditsDomainModule | null = null;
  private earlyWarningsModule: EarlyWarningsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private modelsModule: ModelsDomainModule | null = null;
  private policiesModule: PoliciesDomainModule | null = null;
  private referralsModule: ReferralsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get applications domain module
   */
  getApplicationsDependencies(): ApplicationsDomainModule {
    if (!this.applicationsModule) {
      this.applicationsModule = buildApplicationsDomainModule(this.dynamoClient);
    }
    return this.applicationsModule;
  }

  /**
   * Get audits domain module
   */
  getAuditsDependencies(): AuditsDomainModule {
    if (!this.auditsModule) {
      this.auditsModule = buildAuditsDomainModule(this.dynamoClient);
    }
    return this.auditsModule;
  }

  /**
   * Get early-warnings domain module
   */
  getEarlyWarningsDependencies(): EarlyWarningsDomainModule {
    if (!this.earlyWarningsModule) {
      this.earlyWarningsModule = buildEarlyWarningsDomainModule(this.dynamoClient);
    }
    return this.earlyWarningsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get models domain module
   */
  getModelsDependencies(): ModelsDomainModule {
    if (!this.modelsModule) {
      this.modelsModule = buildModelsDomainModule(this.dynamoClient);
    }
    return this.modelsModule;
  }

  /**
   * Get policies domain module
   */
  getPoliciesDependencies(): PoliciesDomainModule {
    if (!this.policiesModule) {
      this.policiesModule = buildPoliciesDomainModule(this.dynamoClient);
    }
    return this.policiesModule;
  }

  /**
   * Get referrals domain module
   */
  getReferralsDependencies(): ReferralsDomainModule {
    if (!this.referralsModule) {
      this.referralsModule = buildReferralsDomainModule(this.dynamoClient);
    }
    return this.referralsModule;
  }

  clearApplicationsDependencies(): void { this.applicationsModule = null; }
  clearAuditsDependencies(): void { this.auditsModule = null; }
  clearEarlyWarningsDependencies(): void { this.earlyWarningsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearModelsDependencies(): void { this.modelsModule = null; }
  clearPoliciesDependencies(): void { this.policiesModule = null; }
  clearReferralsDependencies(): void { this.referralsModule = null; }

  getApplicationsDependenciesForRequest(): ApplicationsDomainModule {
    return this.getApplicationsDependencies();
  }

  getAuditsDependenciesForRequest(): AuditsDomainModule {
    return this.getAuditsDependencies();
  }

  getEarlyWarningsDependenciesForRequest(): EarlyWarningsDomainModule {
    return this.getEarlyWarningsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getModelsDependenciesForRequest(): ModelsDomainModule {
    return this.getModelsDependencies();
  }

  getPoliciesDependenciesForRequest(): PoliciesDomainModule {
    return this.getPoliciesDependencies();
  }

  getReferralsDependenciesForRequest(): ReferralsDomainModule {
    return this.getReferralsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.applicationsModule = null;
    this.auditsModule = null;
    this.earlyWarningsModule = null;
    this.identityModule = null;
    this.modelsModule = null;
    this.policiesModule = null;
    this.referralsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
