/**
 * ApplicationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApplicationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApplicationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ApplicationRepository,
} from "@lendora/services/applications";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ApplicationRepositoryDdb } from "./application-repository.ddb.js";

/**
 * ApplicationRepositoryAdapter
 *
 * Implements ApplicationRepository port for infrastructure layer.
 */
export class ApplicationRepositoryAdapter implements ApplicationRepository {
  private readonly ddb: ApplicationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ApplicationRepositoryDdb(this.dynamoClient);
  }

  async listApplications(input: Parameters<ApplicationRepository['listApplications']>[0]): Promise<Awaited<ReturnType<ApplicationRepository['listApplications']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listApplications(input);
  }

  async createApplication(input: Parameters<ApplicationRepository['createApplication']>[0]): Promise<Awaited<ReturnType<ApplicationRepository['createApplication']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createApplication(input);
  }

  async getApplication(input: Parameters<ApplicationRepository['getApplication']>[0]): Promise<Awaited<ReturnType<ApplicationRepository['getApplication']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getApplication(input);
  }
}
