/**
 * Repository interface for Decision
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DecisionEntity
} from "../models/decision.entity.js";
import type {
  CreditDecision
} from "../types/index.js";
/**
 * DecisionRepository Interface
 */
export interface DecisionRepository extends CreateReadRepository<DecisionEntity, CreditDecision, string, Record<string, never>> {

}
