/**
 * Repository interface for FeaturePack
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  FeaturePackEntity
} from "../models/feature-pack.entity.js";
import type {
  UpsertApplicationFeaturePackRequestInput
} from "../types/index.js";
/**
 * FeaturePackRepository Interface
 */
export interface FeaturePackRepository extends UpdateReadRepository<FeaturePackEntity, UpsertApplicationFeaturePackRequestInput, string, Record<string, never>> {

}
