/**
 * ListReferTasks handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listReferTasks } from "@lendora/api-server/domains/referrals/handlers";
import type { ReferralsDDDDependencies } from "@lendora/api-server/domains/referrals";
import { createReferTask as createReferTaskEntity } from "@lendora/factories/referrals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { REFERRALS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListReferTasks", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReferralsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReferralsDDDDependencies>(
      REFERRALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createReferTaskEntity({ orgId }),
      createReferTaskEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListReferTasks, "execute").mockResolvedValue(useCaseResult);

    await listReferTasks(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListReferTasks.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
