/**
 * Models DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Models Domain Module - Composition root
 *
 * DDD: Composition root for models domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApprovePromoteRepositoryAdapter,
  CurrentRepositoryAdapter,
  ProposePromoteRepositoryAdapter,
  VModelRepositoryAdapter,
} from "@lendora/adapters/models";
import { getIdGeneratorService } from "@lendora/adapters";
import type { AdapterDynamoDBClient } from "@lendora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApprovePromoteModel,
  ExecuteGetCreditModel,
  ExecuteGetCurrentLearningEnvelope,
  ExecuteListCreditModels,
  ExecuteProposePromoteModel,
  ExecuteRegisterChallengerModel,
  ExecuteUpdateCurrentLearningEnvelope,
} from "@lendora/services/models/usecases";
// Ports (interfaces)
import type {
  ApprovePromoteRepository,
  CurrentRepository,
  ProposePromoteRepository,
  VModelRepository,
} from "@lendora/services/models/ports";

export interface ModelsDomainModule {
  repos: {
    approvePromotes: ApprovePromoteRepository;
    currents: CurrentRepository;
    proposePromotes: ProposePromoteRepository;
    vModels: VModelRepository;
  };
  useCases: {
    approvePromotes: {
      create: ExecuteApprovePromoteModel;
    };
    currents: {
      get: ExecuteGetCurrentLearningEnvelope;
      update: ExecuteUpdateCurrentLearningEnvelope;
    };
    proposePromotes: {
      get: ExecuteProposePromoteModel;
    };
    vModels: {
      create: ExecuteRegisterChallengerModel;
      get: ExecuteGetCreditModel;
      list: ExecuteListCreditModels;
    };
  };
}

export function buildModelsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ModelsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approvePromotes?: ApprovePromoteRepository;
      currents?: CurrentRepository;
      proposePromotes?: ProposePromoteRepository;
      vModels?: VModelRepository;
    } = {};

    obj.approvePromotes = new ApprovePromoteRepositoryAdapter(dynamoClient);
    obj.currents = new CurrentRepositoryAdapter(dynamoClient);
    obj.proposePromotes = new ProposePromoteRepositoryAdapter(dynamoClient);
    obj.vModels = new VModelRepositoryAdapter(dynamoClient);
    return {
      approvePromotes: obj.approvePromotes!,
      currents: obj.currents!,
      proposePromotes: obj.proposePromotes!,
      vModels: obj.vModels!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approvePromotes: {
      create: new ExecuteApprovePromoteModel(executionContext, idGenerator, repos.approvePromotes),
    },
    currents: {
      get: new ExecuteGetCurrentLearningEnvelope(executionContext, idGenerator, repos.currents),
      update: new ExecuteUpdateCurrentLearningEnvelope(executionContext, idGenerator, repos.currents),
    },
    proposePromotes: {
      get: new ExecuteProposePromoteModel(executionContext, idGenerator, repos.proposePromotes),
    },
    vModels: {
      create: new ExecuteRegisterChallengerModel(executionContext, idGenerator, repos.vModels),
      get: new ExecuteGetCreditModel(executionContext, idGenerator, repos.vModels),
      list: new ExecuteListCreditModels(executionContext, idGenerator, repos.vModels),
    },
  };
  return { repos, useCases: useCases as ModelsDomainModule["useCases"] };
}
