/**
 * Current Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/models.openapi.types.js";
import { schemas } from "../schemas/models.schemas.js";

/**
 * Entity: CurrentEntity
 * Description: Represents the Current domain model.
 * Source: schemas.LearningEnvelope
 * Type: Persisted Entity (x-dynamodb)
 */
export const CurrentEntitySchema = schemas.LearningEnvelope;
export type CurrentEntity = components["schemas"]["LearningEnvelope"];
