/**
 * ProposePromote Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/models.openapi.types.js";
import { schemas } from "../schemas/models.schemas.js";

/**
 * Entity: ProposePromoteEntity
 * Description: Represents the ProposePromote domain model.
 * Source: schemas.ModelVersion
 * Type: Persisted Entity (x-dynamodb)
 */
export const ProposePromoteEntitySchema = schemas.ModelVersion;
export type ProposePromoteEntity = components["schemas"]["ModelVersion"];
