/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Applications Domain Use Cases
 * 
 * List of all use case names for the applications domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const APPLICATIONS_USE_CASES = [
  "executeCreateApplication",
  "executeDecideApplication",
  "executeGetApplication",
  "executeGetApplicationDecision",
  "executeGetApplicationFeaturePack",
  "executeGetLendingMetrics",
  "executeListApplications",
  "executeUpsertApplicationFeaturePack"
] as const;
