/**
 * Publish Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PublishEntity } from "@lendora/core/policies/models/index.js";
import { policiesSchemas } from "@lendora/core/policies";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pol";

export function createPublish(overrides: Partial<PublishEntity> = {}) {
  const raw = {
    id: overrides.id ?? `rsn_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    code: overrides.code ?? faker.lorem.word(),
    customerWording: overrides.customerWording ?? faker.lorem.word(),
    status: overrides.status ?? "draft",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    underwriterWording: overrides.underwriterWording ?? faker.lorem.word(),
    ...overrides,
  };

  return policiesSchemas.ReasonCode.parse(raw);
}

export function publishBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPublish(overrides));
}
