/**
 * Policy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PolicyEntity } from "@lendora/core/policies/models/index.js";
import { policiesSchemas } from "@lendora/core/policies";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pol";

export function createPolicy(overrides: Partial<PolicyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `pol_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    productId: overrides.productId ?? faker.string.uuid(),
    productLine: overrides.productLine ?? "personal",
    status: overrides.status ?? "draft",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return policiesSchemas.PolicyPack.parse(raw);
}

export function policyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPolicy(overrides));
}
