/**
 * FeaturePack Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { FeaturePackEntity } from "@lendora/core/applications/models/index.js";
import { applicationsSchemas } from "@lendora/core/applications";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "app";

export function createFeaturePack(overrides: Partial<FeaturePackEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ftp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    applicationId: overrides.applicationId ?? `app_${ulid().toLowerCase()}`,
    provenance: overrides.provenance ?? [],
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return applicationsSchemas.FeaturePack.parse(raw);
}

export function featurePackBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFeaturePack(overrides));
}
