/**
 * DecideApplication handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { decideApplication } from "@lendora/api-server/domains/applications/handlers";
import type { ApplicationsDDDDependencies } from "@lendora/api-server/domains/applications";
import { createDecision as createDecisionEntity } from "@lendora/factories/applications";
import { createCreateDecisionRequest } from "@lendora/factories/applications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { APPLICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("DecideApplication", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ApplicationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ApplicationsDDDDependencies>(
      APPLICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateDecisionRequest();
    const entity = createDecisionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDecideApplication, "execute").mockResolvedValue(useCaseResult);

    await decideApplication(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDecideApplication.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
