/**
 * Repository interface for Acknowledge
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AcknowledgeEntity
} from "../models/acknowledge.entity.js";
import type {
  EarlyWarningAlert
} from "../types/index.js";
/**
 * AcknowledgeRepository Interface
 */
export interface AcknowledgeRepository extends CreateReadRepository<AcknowledgeEntity, EarlyWarningAlert, string, Record<string, never>> {

}
