/**
 * Repository interface for EarlyWarning
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  EarlyWarningEntity
} from "../models/early-warning.entity.js";
import type {
  ListEarlyWarningsParams
} from "../types/index.js";
/**
 * EarlyWarningRepository Interface
 */
export interface EarlyWarningRepository extends ReadRepository<EarlyWarningEntity, string, ListEarlyWarningsParams> {

}
