/**
 * ExecuteListApplications - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListApplications Use Case
 *
 * DDD: Application use case for list Application.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListApplicationsInput, ListApplicationsOutput } from "../dto/application.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ApplicationRepository } from "../ports";

export class ExecuteListApplications {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly application: ApplicationRepository
  ) {}

  async execute(input: ListApplicationsInput): Promise<ListApplicationsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.appId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.application.listApplications({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListApplicationsOutput;
  }
}
