/**
 * ExecuteCreateApplication - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateApplication Use Case
 *
 * DDD: Application use case for create Application.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateApplicationInput, CreateApplicationOutput } from "../dto/application.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ApplicationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateApplication {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly application: ApplicationRepository
  ) {}

  async execute(input: CreateApplicationInput): Promise<CreateApplicationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.appId();

    // All field names extracted from OpenAPI spec: amount, applicantRef, currency, features, productId, productLine
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.amount) {
      throw new ValidationError("amount is required");
    }
    if (!input.productLine) {
      throw new ValidationError("productLine is required");
    }
    if (!input.applicantRef) {
      throw new ValidationError("applicantRef is required");
    }
    if (!input.productId) {
      throw new ValidationError("productId is required");
    }
    if (!input.currency) {
      throw new ValidationError("currency is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (applications domain)
    const entityId = this.idGenerator.appId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.application.createApplication({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateApplicationOutput;
  }
}
