/**
 * ApprovePromote DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApprovePromote DTOs
 *
 * DDD: Application DTOs for ApprovePromote use cases.
 */

import type { ApprovePromoteModelParams } from "@lendora/core/models/types";

export type ApprovePromoteModelInput = ApprovePromoteModelParams;

export type ApprovePromoteModelOutput = {};
