/**
 * Current DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Current DTOs
 *
 * DDD: Application DTOs for Current use cases.
 */

import type { UpdateCurrentLearningEnvelopeRequestInput } from "@lendora/core/models/types";

export type GetCurrentLearningEnvelopeInput = {};

export type UpdateCurrentLearningEnvelopeInput = UpdateCurrentLearningEnvelopeRequestInput;

export type GetCurrentLearningEnvelopeOutput = {};

export type UpdateCurrentLearningEnvelopeOutput = {};
