/**
 * ProposePromote DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProposePromote DTOs
 *
 * DDD: Application DTOs for ProposePromote use cases.
 */

import type { ProposePromoteModelParams } from "@lendora/core/models/types";

export type ProposePromoteModelInput = ProposePromoteModelParams;

export type ProposePromoteModelOutput = {};
