/**
 * VModel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModel DTOs
 *
 * DDD: Application DTOs for VModel use cases.
 */

import type { GetCreditModelParams, ListCreditModelsParams, RegisterChallengerModelRequestInput } from "@lendora/core/models/types";

export type ListCreditModelsInput = ListCreditModelsParams;

export type RegisterChallengerModelInput = RegisterChallengerModelRequestInput;

export type GetCreditModelInput = GetCreditModelParams;

export type ListCreditModelsOutput = {};

export type RegisterChallengerModelOutput = {};

export type GetCreditModelOutput = {};
