/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { approveRoutes } from "./approve.routes.js";
export { policyRoutes } from "./policy.routes.js";
export { publishRoutes } from "./publish.routes.js";
export { reasonCodeRoutes } from "./reason-code.routes.js";
export { rollbackRoutes } from "./rollback.routes.js";
export { simulateRoutes } from "./simulate.routes.js";
export { submitApprovalRoutes } from "./submit-approval.routes.js";
