/**
 * Routes for Policy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPolicyPack, getPolicyPack, listPolicyPacks, updatePolicyPack } from "../handlers/policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function policyRoutes(fastify: FastifyInstance) {
  // POST /v1/policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await createPolicyPack(request, reply, deps);
      });
    }
  );


  // GET /v1/policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await listPolicyPacks(request, reply, deps);
      });
    }
  );


  // GET /v1/policies/{policyPackId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policies/:policyPackId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyPackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await getPolicyPack(request, reply, deps);
      });
    }
  );


  // PATCH /v1/policies/{policyPackId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/policies/:policyPackId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyPackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await updatePolicyPack(request, reply, deps);
      });
    }
  );


}
