/**
 * Routes for ReasonCode
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createReasonCode, getReasonCode, listReasonCodes, updateReasonCode } from "../handlers/reason-code.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function reasonCodeRoutes(fastify: FastifyInstance) {
  // POST /v1/reason-codes (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/reason-codes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await createReasonCode(request, reply, deps);
      });
    }
  );


  // GET /v1/reason-codes (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/reason-codes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await listReasonCodes(request, reply, deps);
      });
    }
  );


  // GET /v1/reason-codes/{reasonCodeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/reason-codes/:reasonCodeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { reasonCodeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await getReasonCode(request, reply, deps);
      });
    }
  );


  // PATCH /v1/reason-codes/{reasonCodeId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/reason-codes/:reasonCodeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { reasonCodeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await updateReasonCode(request, reply, deps);
      });
    }
  );


}
