/**
 * Routes for Simulate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { simulatePolicyVeto } from "../handlers/simulate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function simulateRoutes(fastify: FastifyInstance) {
  // POST /v1/policies/{policyPackId}/simulate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policies/:policyPackId/simulate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyPackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPoliciesDependenciesForRequest();
        await simulatePolicyVeto(request, reply, deps);
      });
    }
  );


}
