/**
 * Routes for Application
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createApplication, getApplication, listApplications } from "../handlers/application.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function applicationRoutes(fastify: FastifyInstance) {
  // POST /v1/applications (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/applications",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getApplicationsDependenciesForRequest();
        await createApplication(request, reply, deps);
      });
    }
  );


  // GET /v1/applications (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/applications",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getApplicationsDependenciesForRequest();
        await listApplications(request, reply, deps);
      });
    }
  );


  // GET /v1/applications/{applicationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/applications/:applicationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getApplicationsDependenciesForRequest();
        await getApplication(request, reply, deps);
      });
    }
  );


}
