/**
 * Routes for Decision
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { decideApplication, getApplicationDecision } from "../handlers/decision.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function decisionRoutes(fastify: FastifyInstance) {
  // POST /v1/applications/{applicationId}/decision (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/applications/:applicationId/decision",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getApplicationsDependenciesForRequest();
        await decideApplication(request, reply, deps);
      });
    }
  );


  // GET /v1/applications/{applicationId}/decision (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/applications/:applicationId/decision",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getApplicationsDependenciesForRequest();
        await getApplicationDecision(request, reply, deps);
      });
    }
  );


}
