/**
 * Routes for FeaturePack
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getApplicationFeaturePack, upsertApplicationFeaturePack } from "../handlers/feature-pack.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function featurePackRoutes(fastify: FastifyInstance) {
  // GET /v1/applications/{applicationId}/feature-pack (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/applications/:applicationId/feature-pack",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getApplicationsDependenciesForRequest();
        await getApplicationFeaturePack(request, reply, deps);
      });
    }
  );


  // PUT /v1/applications/{applicationId}/feature-pack (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/applications/:applicationId/feature-pack",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getApplicationsDependenciesForRequest();
        await upsertApplicationFeaturePack(request, reply, deps);
      });
    }
  );


}
