/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { metricRoutes } from "./metric.routes.js";
export { applicationRoutes } from "./application.routes.js";
export { decisionRoutes } from "./decision.routes.js";
export { featurePackRoutes } from "./feature-pack.routes.js";
