/**
 * Current Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CurrentEntity } from "@lendora/core/models/models/index.js";
import { modelsSchemas } from "@lendora/core/models";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mdl";

export function createCurrent(overrides: Partial<CurrentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `env_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    locked: overrides.locked ?? faker.datatype.boolean(),
    maxLoosenPct: overrides.maxLoosenPct ?? faker.number.int(),
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return modelsSchemas.LearningEnvelope.parse(raw);
}

export function currentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCurrent(overrides));
}
