/**
 * EarlyWarning Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EarlyWarningEntity } from "@lendora/core/early-warnings/models/index.js";
import { earlyWarningsSchemas } from "@lendora/core/early-warnings";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ews";

export function createEarlyWarning(overrides: Partial<EarlyWarningEntity> = {}) {
  const raw = {
    id: overrides.id ?? `ews_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    accountId: overrides.accountId ?? faker.string.uuid(),
    severity: overrides.severity ?? "low",
    signal: overrides.signal ?? faker.lorem.word(),
    status: overrides.status ?? "open",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    vintageWindow: overrides.vintageWindow ?? faker.lorem.word(),
    ...overrides,
  };

  return earlyWarningsSchemas.EarlyWarningAlert.parse(raw);
}

export function earlyWarningBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEarlyWarning(overrides));
}
