/**
 * Repository interface for Approve
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ApproveEntity
} from "../models/approve.entity.js";
import type {
  PolicyPack
} from "../types/index.js";
/**
 * ApproveRepository Interface
 */
export interface ApproveRepository extends CreateReadRepository<ApproveEntity, PolicyPack, string, Record<string, never>> {

}
