/**
 * Repository interface for Publish
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  PublishEntity
} from "../models/publish.entity.js";
import type {
  ReasonCode
} from "../types/index.js";
/**
 * PublishRepository Interface
 */
export interface PublishRepository extends CreateReadRepository<PublishEntity, ReasonCode, string, Record<string, never>> {

}
