/**
 * Repository interface for ReasonCode
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ReasonCodeEntity
} from "../models/reason-code.entity.js";
import type {
  ListReasonCodesParams,
  ReasonCode,
  UpdateReasonCodeRequestInput
} from "../types/index.js";
/**
 * ReasonCodeRepository Interface
 */
export interface ReasonCodeRepository extends CreateUpdateReadRepository<ReasonCodeEntity, ReasonCode, UpdateReasonCodeRequestInput, string, ListReasonCodesParams> {

}
