/**
 * Repository interface for SubmitApproval
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SubmitApprovalEntity
} from "../models/submit-approval.entity.js";
import type {
  PolicyPack
} from "../types/index.js";
/**
 * SubmitApprovalRepository Interface
 */
export interface SubmitApprovalRepository extends CreateReadRepository<SubmitApprovalEntity, PolicyPack, string, Record<string, never>> {

}
