/**
 * GetApplicationFeaturePack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getApplicationFeaturePack } from "@lendora/api-server/domains/applications/handlers";
import type { ApplicationsDDDDependencies } from "@lendora/api-server/domains/applications";
import { createFeaturePack as createFeaturePackEntity } from "@lendora/factories/applications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { APPLICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetApplicationFeaturePack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ApplicationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ApplicationsDDDDependencies>(
      APPLICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createFeaturePackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetApplicationFeaturePack, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { applicationId: entity.id };

    await getApplicationFeaturePack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetApplicationFeaturePack.execute).toHaveBeenCalledWith(expect.objectContaining({ applicationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { applicationId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetApplicationFeaturePack, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getApplicationFeaturePack(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
