/**
 * Audit Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/audits.openapi.types.js";
import { schemas } from "../schemas/audits.schemas.js";

/**
 * Entity: AuditEntity
 * Description: Represents the Audit domain model.
 * Source: schemas.DecisionAudit
 * Type: Persisted Entity (x-dynamodb)
 */
export const AuditEntitySchema = schemas.DecisionAudit;
export type AuditEntity = components["schemas"]["DecisionAudit"];
