/**
 * Repository interface for Audit
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AuditEntity
} from "../models/audit.entity.js";
import type {
  ListDecisionAuditsParams,
  DecisionAudit
} from "../types/index.js";
/**
 * AuditRepository Interface
 */
export interface AuditRepository extends CreateReadRepository<AuditEntity, DecisionAudit, string, ListDecisionAuditsParams> {

}
