/**
 * Repository interface for ByApplication
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ByApplicationEntity
} from "../models/by-application.entity.js";
/**
 * ByApplicationRepository Interface
 */
export interface ByApplicationRepository extends ReadRepository<ByApplicationEntity, string, Record<string, never>> {

}
