/**
 * ClaimRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClaimRepository Port
 *
 * DDD: Application port for claimrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ClaimReferTaskInput, ClaimReferTaskOutput } from "../dto/claim.dto";
export interface ClaimRepository {
  claimReferTask(input: ClaimReferTaskInput): Promise<ClaimReferTaskOutput>;
}

export type { ClaimReferTaskInput, ClaimReferTaskOutput } from "../dto/claim.dto";
