/**
 * ReferTaskRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReferTaskRepository Port
 *
 * DDD: Application port for refertaskrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetReferTaskInput, GetReferTaskOutput, ListReferTasksInput, ListReferTasksOutput } from "../dto/refer-task.dto";
export interface ReferTaskRepository {
  listReferTasks(input: ListReferTasksInput): Promise<ListReferTasksOutput>;
  getReferTask(input: GetReferTaskInput): Promise<GetReferTaskOutput>;
}

export type { GetReferTaskInput, GetReferTaskOutput, ListReferTasksInput, ListReferTasksOutput } from "../dto/refer-task.dto";
