/**
 * ListAudit DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDecisionAuditsParams } from "@lendora/core/audits";

export function createListAuditRequest(overrides: Partial<ListDecisionAuditsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
