/**
 * RollbackPolicyPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { rollbackPolicyPack } from "@lendora/api-server/domains/policies/handlers";
import type { PoliciesDDDDependencies } from "@lendora/api-server/domains/policies";
import { createRollback as createRollbackEntity } from "@lendora/factories/policies";
import { createCreateRollbackRequest } from "@lendora/factories/policies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { POLICIES_USE_CASES } from "../__factories__/use-cases.js";

describe("RollbackPolicyPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PoliciesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PoliciesDDDDependencies>(
      POLICIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateRollbackRequest();
    const entity = createRollbackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRollbackPolicyPack, "execute").mockResolvedValue(useCaseResult);

    await rollbackPolicyPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRollbackPolicyPack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
