/**
 * EarlyWarningRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EarlyWarningRepository Port
 *
 * DDD: Application port for earlywarningrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEarlyWarningInput, GetEarlyWarningOutput, ListEarlyWarningsInput, ListEarlyWarningsOutput } from "../dto/early-warning.dto";
export interface EarlyWarningRepository {
  listEarlyWarnings(input: ListEarlyWarningsInput): Promise<ListEarlyWarningsOutput>;
  getEarlyWarning(input: GetEarlyWarningInput): Promise<GetEarlyWarningOutput>;
}

export type { GetEarlyWarningInput, GetEarlyWarningOutput, ListEarlyWarningsInput, ListEarlyWarningsOutput } from "../dto/early-warning.dto";
