/**
 * GetVModel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCreditModelParams } from "@lendora/core/models";

export function createGetVModelRequest(overrides: Partial<GetCreditModelParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
