/**
 * ReasonCode DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReasonCode DTOs
 *
 * DDD: Application DTOs for ReasonCode use cases.
 */

import type { CreateReasonCodeRequestInput, GetReasonCodeParams, ListReasonCodesParams, UpdateReasonCodeParams, UpdateReasonCodeRequestInput } from "@lendora/core/policies/types";

export type ListReasonCodesInput = ListReasonCodesParams;

export type CreateReasonCodeInput = CreateReasonCodeRequestInput;

export type GetReasonCodeInput = GetReasonCodeParams;

export type UpdateReasonCodeInput = UpdateReasonCodeParams & UpdateReasonCodeRequestInput;

export type ListReasonCodesOutput = {};

export type CreateReasonCodeOutput = {};

export type GetReasonCodeOutput = {};

export type UpdateReasonCodeOutput = {};
