/**
 * Rollback DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Rollback DTOs
 *
 * DDD: Application DTOs for Rollback use cases.
 */

import type { RollbackPolicyPackParams } from "@lendora/core/policies/types";

export type RollbackPolicyPackInput = RollbackPolicyPackParams;

export type RollbackPolicyPackOutput = {};
