/**
 * Simulate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Simulate DTOs
 *
 * DDD: Application DTOs for Simulate use cases.
 */

import type { SimulatePolicyVetoParams, SimulatePolicyVetoRequestInput } from "@lendora/core/policies/types";

export type SimulatePolicyVetoInput = SimulatePolicyVetoParams & SimulatePolicyVetoRequestInput;

export type SimulatePolicyVetoOutput = {};
