/**
 * SubmitApproval DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitApproval DTOs
 *
 * DDD: Application DTOs for SubmitApproval use cases.
 */

import type { SubmitPolicyPackApprovalParams } from "@lendora/core/policies/types";

export type SubmitPolicyPackApprovalInput = SubmitPolicyPackApprovalParams;

export type SubmitPolicyPackApprovalOutput = {};
