/**
 * GetReasonCode DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetReasonCodeParams } from "@lendora/core/policies";

export function createGetReasonCodeRequest(overrides: Partial<GetReasonCodeParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
