/**
 * Application Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ApplicationEntity } from "@lendora/core/applications/models/index.js";
import { applicationsSchemas } from "@lendora/core/applications";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "app";

export function createApplication(overrides: Partial<ApplicationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `app_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    amount: overrides.amount ?? faker.number.int(),
    applicantRef: overrides.applicantRef ?? faker.lorem.word(),
    currency: overrides.currency ?? faker.lorem.word(),
    productId: overrides.productId ?? faker.string.uuid(),
    productLine: overrides.productLine ?? "personal",
    status: overrides.status ?? "received",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return applicationsSchemas.Application.parse(raw);
}

export function applicationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createApplication(overrides));
}
