/**
 * Handlers for Application
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ApplicationsDomainModule } from "../dependencies/applications-ddd.dependencies.js";
import type { CreateApplicationInput, GetApplicationInput, ListApplicationsInput } from "@lendora/services/applications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/applications
 * Operation: listApplications
 */
export async function listApplications(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], productLine?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ApplicationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListApplicationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.applications.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/applications
 * Operation: createApplication
 */
export async function createApplication(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ApplicationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateApplicationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.applications.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/applications/{applicationId}
 * Operation: getApplication
 */
export async function getApplication(
  request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ApplicationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetApplicationInput = {
    applicationId: request.params.applicationId,
  };
  const result = await deps.useCases.applications.get.execute(input);
  return reply.code(200).send(result);
}


