/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ApplicationsDomainModule } from "../dependencies/applications-ddd.dependencies.js";
import type { DecideApplicationInput, GetApplicationDecisionInput } from "@lendora/services/applications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/applications/{applicationId}/decision
 * Operation: getApplicationDecision
 */
export async function getApplicationDecision(
  request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ApplicationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetApplicationDecisionInput = {
    applicationId: request.params.applicationId,
  };
  const result = await deps.useCases.decisions.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/applications/{applicationId}/decision
 * Operation: decideApplication
 */
export async function decideApplication(
  request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ApplicationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideApplicationInput = {
    applicationId: request.params.applicationId,
  };
  const result = await deps.useCases.decisions.decide.execute(input);
  return reply.code(201).send(result);
}


