/**
 * Handlers for FeaturePack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ApplicationsDomainModule } from "../dependencies/applications-ddd.dependencies.js";
import type { GetApplicationFeaturePackInput, UpsertApplicationFeaturePackInput } from "@lendora/services/applications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/applications/{applicationId}/feature-pack
 * Operation: getApplicationFeaturePack
 */
export async function getApplicationFeaturePack(
  request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ApplicationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetApplicationFeaturePackInput = {
    applicationId: request.params.applicationId,
  };
  const result = await deps.useCases.featurePacks.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/applications/{applicationId}/feature-pack
 * Operation: upsertApplicationFeaturePack
 */
export async function upsertApplicationFeaturePack(
  request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ApplicationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertApplicationFeaturePackInput = {
    applicationId: request.params.applicationId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.featurePacks.get.execute(input);
  return reply.code(200).send(result);
}


