/**
 * Repository interface for Claim
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ClaimEntity
} from "../models/claim.entity.js";
import type {
  ReferTask
} from "../types/index.js";
/**
 * ClaimRepository Interface
 */
export interface ClaimRepository extends CreateReadRepository<ClaimEntity, ReferTask, string, Record<string, never>> {

}
