/**
 * Repository interface for Override
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  OverrideEntity
} from "../models/override.entity.js";
import type {
  Override
} from "../types/index.js";
/**
 * OverrideRepository Interface
 */
export interface OverrideRepository extends CreateReadRepository<OverrideEntity, Override, string, Record<string, never>> {

}
