/**
 * Repository interface for ReferTask
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ReferTaskEntity
} from "../models/refer-task.entity.js";
import type {
  ListReferTasksParams
} from "../types/index.js";
/**
 * ReferTaskRepository Interface
 */
export interface ReferTaskRepository extends ReadRepository<ReferTaskEntity, string, ListReferTasksParams> {

}
