/**
 * Repository interface for ApprovePromote
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ApprovePromoteEntity
} from "../models/approve-promote.entity.js";
import type {
  ModelVersion
} from "../types/index.js";
/**
 * ApprovePromoteRepository Interface
 */
export interface ApprovePromoteRepository extends CreateReadRepository<ApprovePromoteEntity, ModelVersion, string, Record<string, never>> {

}
