/**
 * Repository interface for Current
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CurrentEntity
} from "../models/current.entity.js";
import type {
  UpdateCurrentLearningEnvelopeRequestInput
} from "../types/index.js";
/**
 * CurrentRepository Interface
 */
export interface CurrentRepository extends UpdateReadRepository<CurrentEntity, UpdateCurrentLearningEnvelopeRequestInput, string, Record<string, never>> {

}
