/**
 * Repository interface for ProposePromote
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProposePromoteEntity
} from "../models/propose-promote.entity.js";
import type {
  ModelVersion
} from "../types/index.js";
/**
 * ProposePromoteRepository Interface
 */
export interface ProposePromoteRepository extends CreateReadRepository<ProposePromoteEntity, ModelVersion, string, Record<string, never>> {

}
