/**
 * Repository interface for VModel
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  VModelEntity
} from "../models/vmodel.entity.js";
import type {
  ListCreditModelsParams,
  ModelVersion
} from "../types/index.js";
/**
 * VModelRepository Interface
 */
export interface VModelRepository extends CreateReadRepository<VModelEntity, ModelVersion, string, ListCreditModelsParams> {

}
