/**
 * ExecuteEscalateEarlyWarning - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteEscalateEarlyWarning Use Case
 *
 * DDD: Application use case for get Escalate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { EscalateEarlyWarningInput, EscalateEarlyWarningOutput } from "../dto/escalate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { EscalateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteEscalateEarlyWarning {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly escalate: EscalateRepository
  ) {}

  async execute(input: EscalateEarlyWarningInput): Promise<EscalateEarlyWarningOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ewsId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).alertId) {
      throw new ValidationError("alertId is required");
    }
    const alertId = (input as any).alertId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.escalate.escalateEarlyWarning({ alertId: alertId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${alertId}`);
    }

    return entity as EscalateEarlyWarningOutput;
  }
}
