/**
 * SubmitPolicyPackApproval handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { submitPolicyPackApproval } from "@lendora/api-server/domains/policies/handlers";
import type { PoliciesDDDDependencies } from "@lendora/api-server/domains/policies";
import { createSubmitApproval as createSubmitApprovalEntity } from "@lendora/factories/policies";
import { createCreateSubmitApprovalRequest } from "@lendora/factories/policies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { POLICIES_USE_CASES } from "../__factories__/use-cases.js";

describe("SubmitPolicyPackApproval", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PoliciesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PoliciesDDDDependencies>(
      POLICIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateSubmitApprovalRequest();
    const entity = createSubmitApprovalEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSubmitPolicyPackApproval, "execute").mockResolvedValue(useCaseResult);

    await submitPolicyPackApproval(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSubmitPolicyPackApproval.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
