/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @lendora/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@lendora/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@lendora/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@lendora/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@lendora/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@lendora/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _applications from "./applications/index.js";
import * as _audits from "./audits/index.js";
import * as _earlyWarnings from "./early-warnings/index.js";
import * as _identity from "./identity/index.js";
import * as _models from "./models/index.js";
import * as _policies from "./policies/index.js";
import * as _referrals from "./referrals/index.js";

// Export as namespaces
export const _shared = __shared;
export const applications = _applications;
export const audits = _audits;
export const earlyWarnings = _earlyWarnings;
export const identity = _identity;
export const models = _models;
export const policies = _policies;
export const referrals = _referrals;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@lendora/core"; activity.types.*
//   - Direct exports: import * from "@lendora/core/activity/types/index.js"
//   - Direct exports: import * from "@lendora/core/activity/repositories/index.js"
//   - Direct exports: import * from "@lendora/core/activity/models/index.js"
//   - Direct exports: import * from "@lendora/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Applications Service
export { schemas as ApplicationsSchemas } from "./applications/schemas/applications.schemas.js";

// Audits Service
export { schemas as AuditsSchemas } from "./audits/schemas/audits.schemas.js";

// EarlyWarnings Service
export { schemas as EarlyWarningsSchemas } from "./early-warnings/schemas/early-warnings.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Models Service
export { schemas as ModelsSchemas } from "./models/schemas/models.schemas.js";

// Policies Service
export { schemas as PoliciesSchemas } from "./policies/schemas/policies.schemas.js";

// Referrals Service
export { schemas as ReferralsSchemas } from "./referrals/schemas/referrals.schemas.js";

