/**
 * Rollback Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/policies.openapi.types.js";
import { schemas } from "../schemas/policies.schemas.js";

/**
 * Entity: RollbackEntity
 * Description: Represents the Rollback domain model.
 * Source: schemas.PolicyPack
 * Type: Persisted Entity (x-dynamodb)
 */
export const RollbackEntitySchema = schemas.PolicyPack;
export type RollbackEntity = components["schemas"]["PolicyPack"];
