/**
 * ApprovePromoteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApprovePromoteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApprovePromoteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ApprovePromoteRepository,
} from "@lendora/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ApprovePromoteRepositoryDdb } from "./approve-promote-repository.ddb.js";

/**
 * ApprovePromoteRepositoryAdapter
 *
 * Implements ApprovePromoteRepository port for infrastructure layer.
 */
export class ApprovePromoteRepositoryAdapter implements ApprovePromoteRepository {
  private readonly ddb: ApprovePromoteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ApprovePromoteRepositoryDdb(this.dynamoClient);
  }

  async approvePromoteModel(input: Parameters<ApprovePromoteRepository['approvePromoteModel']>[0]): Promise<Awaited<ReturnType<ApprovePromoteRepository['approvePromoteModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.approvePromoteModel(input);
  }
}
