/**
 * CurrentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CurrentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CurrentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CurrentRepository,
} from "@lendora/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CurrentRepositoryDdb } from "./current-repository.ddb.js";

/**
 * CurrentRepositoryAdapter
 *
 * Implements CurrentRepository port for infrastructure layer.
 */
export class CurrentRepositoryAdapter implements CurrentRepository {
  private readonly ddb: CurrentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CurrentRepositoryDdb(this.dynamoClient);
  }

  async getCurrentLearningEnvelope(input: Parameters<CurrentRepository['getCurrentLearningEnvelope']>[0]): Promise<Awaited<ReturnType<CurrentRepository['getCurrentLearningEnvelope']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCurrentLearningEnvelope(input);
  }

  async updateCurrentLearningEnvelope(input: Parameters<CurrentRepository['updateCurrentLearningEnvelope']>[0]): Promise<Awaited<ReturnType<CurrentRepository['updateCurrentLearningEnvelope']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateCurrentLearningEnvelope(input);
  }
}
