/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-promote-repository.ddb.js";
export * from "./current-repository.ddb.js";
export * from "./propose-promote-repository.ddb.js";
export * from "./vmodel-repository.ddb.js";
export * from "./approve-promote-repository.adapter.js";
export * from "./current-repository.adapter.js";
export * from "./propose-promote-repository.adapter.js";
export * from "./vmodel-repository.adapter.js";
