/**
 * ProposePromoteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProposePromoteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProposePromoteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProposePromoteRepository,
} from "@lendora/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProposePromoteRepositoryDdb } from "./propose-promote-repository.ddb.js";

/**
 * ProposePromoteRepositoryAdapter
 *
 * Implements ProposePromoteRepository port for infrastructure layer.
 */
export class ProposePromoteRepositoryAdapter implements ProposePromoteRepository {
  private readonly ddb: ProposePromoteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProposePromoteRepositoryDdb(this.dynamoClient);
  }

  async proposePromoteModel(input: Parameters<ProposePromoteRepository['proposePromoteModel']>[0]): Promise<Awaited<ReturnType<ProposePromoteRepository['proposePromoteModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.proposePromoteModel(input);
  }
}
