/**
 * EarlyWarning DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EarlyWarning DTOs
 *
 * DDD: Application DTOs for EarlyWarning use cases.
 */

import type { GetEarlyWarningParams, ListEarlyWarningsParams } from "@lendora/core/early-warnings/types";

export type ListEarlyWarningsInput = ListEarlyWarningsParams;

export type GetEarlyWarningInput = GetEarlyWarningParams;

export type ListEarlyWarningsOutput = {};

export type GetEarlyWarningOutput = {};
