/**
 * Escalate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Escalate DTOs
 *
 * DDD: Application DTOs for Escalate use cases.
 */

import type { EscalateEarlyWarningParams } from "@lendora/core/early-warnings/types";

export type EscalateEarlyWarningInput = EscalateEarlyWarningParams;

export type EscalateEarlyWarningOutput = {};
