/**
 * CreatePublish DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { PublishReasonCodeParams } from "@lendora/core/policies";

export function createCreatePublishRequest(overrides: Partial<PublishReasonCodeParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
