/**
 * Audit DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Audit DTOs
 *
 * DDD: Application DTOs for Audit use cases.
 */

import type { CreateDecisionAuditRequestInput, GetDecisionAuditParams, ListDecisionAuditsParams } from "@lendora/core/audits/types";

export type ListDecisionAuditsInput = ListDecisionAuditsParams;

export type CreateDecisionAuditInput = CreateDecisionAuditRequestInput;

export type GetDecisionAuditInput = GetDecisionAuditParams;

export type ListDecisionAuditsOutput = {};

export type CreateDecisionAuditOutput = {};

export type GetDecisionAuditOutput = {};
