/**
 * ByApplication DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ByApplication DTOs
 *
 * DDD: Application DTOs for ByApplication use cases.
 */

import type { GetDecisionAuditByApplicationParams } from "@lendora/core/audits/types";

export type GetDecisionAuditByApplicationInput = GetDecisionAuditByApplicationParams;

export type GetDecisionAuditByApplicationOutput = {};
