/**
 * PolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRepository Port
 *
 * DDD: Application port for policyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreatePolicyPackInput, CreatePolicyPackOutput, GetPolicyPackInput, GetPolicyPackOutput, ListPolicyPacksInput, ListPolicyPacksOutput, UpdatePolicyPackInput, UpdatePolicyPackOutput } from "../dto/policy.dto";
export interface PolicyRepository {
  listPolicyPacks(input: ListPolicyPacksInput): Promise<ListPolicyPacksOutput>;
  createPolicyPack(input: CreatePolicyPackInput): Promise<CreatePolicyPackOutput>;
  getPolicyPack(input: GetPolicyPackInput): Promise<GetPolicyPackOutput>;
  updatePolicyPack(input: UpdatePolicyPackInput): Promise<UpdatePolicyPackOutput>;
}

export type { CreatePolicyPackInput, CreatePolicyPackOutput, GetPolicyPackInput, GetPolicyPackOutput, ListPolicyPacksInput, ListPolicyPacksOutput, UpdatePolicyPackInput, UpdatePolicyPackOutput } from "../dto/policy.dto";
