/**
 * PublishPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PublishPublisher Port
 *
 * DDD: Application port for publishpublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PublishReasonCodeInput, PublishReasonCodeOutput } from "../dto/publish.dto";
export interface PublishPublisher {
  publishReasonCode(input: PublishReasonCodeInput): Promise<PublishReasonCodeOutput>;
}

export type { PublishReasonCodeInput, PublishReasonCodeOutput } from "../dto/publish.dto";
