/**
 * ReasonCodeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReasonCodeRepository Port
 *
 * DDD: Application port for reasoncoderepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateReasonCodeInput, CreateReasonCodeOutput, GetReasonCodeInput, GetReasonCodeOutput, ListReasonCodesInput, ListReasonCodesOutput, UpdateReasonCodeInput, UpdateReasonCodeOutput } from "../dto/reason-code.dto";
export interface ReasonCodeRepository {
  listReasonCodes(input: ListReasonCodesInput): Promise<ListReasonCodesOutput>;
  createReasonCode(input: CreateReasonCodeInput): Promise<CreateReasonCodeOutput>;
  getReasonCode(input: GetReasonCodeInput): Promise<GetReasonCodeOutput>;
  updateReasonCode(input: UpdateReasonCodeInput): Promise<UpdateReasonCodeOutput>;
}

export type { CreateReasonCodeInput, CreateReasonCodeOutput, GetReasonCodeInput, GetReasonCodeOutput, ListReasonCodesInput, ListReasonCodesOutput, UpdateReasonCodeInput, UpdateReasonCodeOutput } from "../dto/reason-code.dto";
