/**
 * RollbackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RollbackRepository Port
 *
 * DDD: Application port for rollbackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RollbackPolicyPackInput, RollbackPolicyPackOutput } from "../dto/rollback.dto";
export interface RollbackRepository {
  rollbackPolicyPack(input: RollbackPolicyPackInput): Promise<RollbackPolicyPackOutput>;
}

export type { RollbackPolicyPackInput, RollbackPolicyPackOutput } from "../dto/rollback.dto";
