/**
 * SimulateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SimulateRepository Port
 *
 * DDD: Application port for simulaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SimulatePolicyVetoInput, SimulatePolicyVetoOutput } from "../dto/simulate.dto";
export interface SimulateRepository {
  simulatePolicyVeto(input: SimulatePolicyVetoInput): Promise<SimulatePolicyVetoOutput>;
}

export type { SimulatePolicyVetoInput, SimulatePolicyVetoOutput } from "../dto/simulate.dto";
