/**
 * Application DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Application DTOs
 *
 * DDD: Application DTOs for Application use cases.
 */

import type { CreateApplicationRequestInput, GetApplicationParams, ListApplicationsParams } from "@lendora/core/applications/types";

export type ListApplicationsInput = ListApplicationsParams;

export type CreateApplicationInput = CreateApplicationRequestInput;

export type GetApplicationInput = GetApplicationParams;

export type ListApplicationsOutput = {};

export type CreateApplicationOutput = {};

export type GetApplicationOutput = {};
