/**
 * Decision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decision DTOs
 *
 * DDD: Application DTOs for Decision use cases.
 */

import type { DecideApplicationParams, GetApplicationDecisionParams } from "@lendora/core/applications/types";

export type GetApplicationDecisionInput = GetApplicationDecisionParams;

export type DecideApplicationInput = DecideApplicationParams;

export type GetApplicationDecisionOutput = {};

export type DecideApplicationOutput = {};
