/**
 * FeaturePack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FeaturePack DTOs
 *
 * DDD: Application DTOs for FeaturePack use cases.
 */

import type { GetApplicationFeaturePackParams, UpsertApplicationFeaturePackParams, UpsertApplicationFeaturePackRequestInput } from "@lendora/core/applications/types";

export type GetApplicationFeaturePackInput = GetApplicationFeaturePackParams;

export type UpsertApplicationFeaturePackInput = UpsertApplicationFeaturePackParams & UpsertApplicationFeaturePackRequestInput;

export type GetApplicationFeaturePackOutput = {};

export type UpsertApplicationFeaturePackOutput = {};
