/**
 * AuditRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AuditRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AuditRepository,
} from "@lendora/services/audits";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AuditRepositoryDdb } from "./audit-repository.ddb.js";

/**
 * AuditRepositoryAdapter
 *
 * Implements AuditRepository port for infrastructure layer.
 */
export class AuditRepositoryAdapter implements AuditRepository {
  private readonly ddb: AuditRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AuditRepositoryDdb(this.dynamoClient);
  }

  async listDecisionAudits(input: Parameters<AuditRepository['listDecisionAudits']>[0]): Promise<Awaited<ReturnType<AuditRepository['listDecisionAudits']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDecisionAudits(input);
  }

  async createDecisionAudit(input: Parameters<AuditRepository['createDecisionAudit']>[0]): Promise<Awaited<ReturnType<AuditRepository['createDecisionAudit']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDecisionAudit(input);
  }

  async getDecisionAudit(input: Parameters<AuditRepository['getDecisionAudit']>[0]): Promise<Awaited<ReturnType<AuditRepository['getDecisionAudit']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDecisionAudit(input);
  }
}
