/**
 * ByApplicationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ByApplicationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ByApplicationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ByApplicationRepository,
} from "@lendora/services/audits";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ByApplicationRepositoryDdb } from "./by-application-repository.ddb.js";

/**
 * ByApplicationRepositoryAdapter
 *
 * Implements ByApplicationRepository port for infrastructure layer.
 */
export class ByApplicationRepositoryAdapter implements ByApplicationRepository {
  private readonly ddb: ByApplicationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ByApplicationRepositoryDdb(this.dynamoClient);
  }

  async getDecisionAuditByApplication(input: Parameters<ByApplicationRepository['getDecisionAuditByApplication']>[0]): Promise<Awaited<ReturnType<ByApplicationRepository['getDecisionAuditByApplication']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDecisionAuditByApplication(input);
  }
}
