/**
 * AcknowledgeEarlyWarning handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { acknowledgeEarlyWarning } from "@lendora/api-server/domains/early-warnings/handlers";
import type { EarlyWarningsDDDDependencies } from "@lendora/api-server/domains/early-warnings";
import { createAcknowledge as createAcknowledgeEntity } from "@lendora/factories/early-warnings";
import { createCreateAcknowledgeRequest } from "@lendora/factories/early-warnings";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { EARLYWARNINGS_USE_CASES } from "../__factories__/use-cases.js";

describe("AcknowledgeEarlyWarning", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EarlyWarningsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EarlyWarningsDDDDependencies>(
      EARLYWARNINGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateAcknowledgeRequest();
    const entity = createAcknowledgeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAcknowledgeEarlyWarning, "execute").mockResolvedValue(useCaseResult);

    await acknowledgeEarlyWarning(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAcknowledgeEarlyWarning.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
