/**
 * PolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PolicyRepository,
} from "@lendora/services/policies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PolicyRepositoryDdb } from "./policy-repository.ddb.js";

/**
 * PolicyRepositoryAdapter
 *
 * Implements PolicyRepository port for infrastructure layer.
 */
export class PolicyRepositoryAdapter implements PolicyRepository {
  private readonly ddb: PolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PolicyRepositoryDdb(this.dynamoClient);
  }

  async listPolicyPacks(input: Parameters<PolicyRepository['listPolicyPacks']>[0]): Promise<Awaited<ReturnType<PolicyRepository['listPolicyPacks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPolicyPacks(input);
  }

  async createPolicyPack(input: Parameters<PolicyRepository['createPolicyPack']>[0]): Promise<Awaited<ReturnType<PolicyRepository['createPolicyPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPolicyPack(input);
  }

  async getPolicyPack(input: Parameters<PolicyRepository['getPolicyPack']>[0]): Promise<Awaited<ReturnType<PolicyRepository['getPolicyPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPolicyPack(input);
  }

  async updatePolicyPack(input: Parameters<PolicyRepository['updatePolicyPack']>[0]): Promise<Awaited<ReturnType<PolicyRepository['updatePolicyPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updatePolicyPack(input);
  }
}
