/**
 * ReferTask Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ReferTaskEntity } from "@lendora/core/referrals/models/index.js";
import { referralsSchemas } from "@lendora/core/referrals";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ref";

export function createReferTask(overrides: Partial<ReferTaskEntity> = {}) {
  const raw = {
    id: overrides.id ?? `rft_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    applicationId: overrides.applicationId ?? faker.string.uuid(),
    decisionId: overrides.decisionId ?? faker.string.uuid(),
    reasonCodes: overrides.reasonCodes ?? [],
    status: overrides.status ?? "open",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return referralsSchemas.ReferTask.parse(raw);
}

export function referTaskBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createReferTask(overrides));
}
