/**
 * Audits DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Audits Domain Module - Composition root
 *
 * DDD: Composition root for audits domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AuditRepositoryAdapter,
  ByApplicationRepositoryAdapter,
} from "@lendora/adapters/audits";
import { getIdGeneratorService } from "@lendora/adapters";
import type { AdapterDynamoDBClient } from "@lendora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDecisionAudit,
  ExecuteGetDecisionAudit,
  ExecuteGetDecisionAuditByApplication,
  ExecuteListDecisionAudits,
} from "@lendora/services/audits/usecases";
// Ports (interfaces)
import type {
  AuditRepository,
  ByApplicationRepository,
} from "@lendora/services/audits/ports";

export interface AuditsDomainModule {
  repos: {
    audits: AuditRepository;
    byApplications: ByApplicationRepository;
  };
  useCases: {
    audits: {
      create: ExecuteCreateDecisionAudit;
      get: ExecuteGetDecisionAudit;
      list: ExecuteListDecisionAudits;
    };
    byApplications: {
      get: ExecuteGetDecisionAuditByApplication;
    };
  };
}

export function buildAuditsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AuditsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      audits?: AuditRepository;
      byApplications?: ByApplicationRepository;
    } = {};

    obj.audits = new AuditRepositoryAdapter(dynamoClient);
    obj.byApplications = new ByApplicationRepositoryAdapter(dynamoClient);
    return {
      audits: obj.audits!,
      byApplications: obj.byApplications!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    audits: {
      create: new ExecuteCreateDecisionAudit(executionContext, idGenerator, repos.audits),
      get: new ExecuteGetDecisionAudit(executionContext, idGenerator, repos.audits),
      list: new ExecuteListDecisionAudits(executionContext, idGenerator, repos.audits),
    },
    byApplications: {
      get: new ExecuteGetDecisionAuditByApplication(executionContext, idGenerator, repos.byApplications),
    },
  };
  return { repos, useCases: useCases as AuditsDomainModule["useCases"] };
}
