/**
 * ExecuteProposePromoteModel - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteProposePromoteModel Use Case
 *
 * DDD: Application use case for get ProposePromote.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ProposePromoteModelInput, ProposePromoteModelOutput } from "../dto/propose-promote.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ProposePromoteRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteProposePromoteModel {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly proposePromote: ProposePromoteRepository
  ) {}

  async execute(input: ProposePromoteModelInput): Promise<ProposePromoteModelOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelVersionId) {
      throw new ValidationError("modelVersionId is required");
    }
    const modelversionId = (input as any).modelVersionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.proposePromote.proposePromoteModel({ modelVersionId: modelversionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelversionId}`);
    }

    return entity as ProposePromoteModelOutput;
  }
}
