/**
 * ExecuteRegisterChallengerModel - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterChallengerModel Use Case
 *
 * DDD: Application use case for create VModel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterChallengerModelInput, RegisterChallengerModelOutput } from "../dto/vmodel.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { VModelRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterChallengerModel {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vModel: VModelRepository
  ) {}

  async execute(input: RegisterChallengerModelInput): Promise<RegisterChallengerModelOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec: discriminationScore, name, role, stabilityScore
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.role) {
      throw new ValidationError("role is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (models domain)
    const entityId = this.idGenerator.mdlId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.vModel.registerChallengerModel({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterChallengerModelOutput;
  }
}
