/**
 * ExecuteUpdateCurrentLearningEnvelope - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateCurrentLearningEnvelope Use Case
 *
 * DDD: Application use case for update Current.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateCurrentLearningEnvelopeInput, UpdateCurrentLearningEnvelopeOutput } from "../dto/current.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { CurrentRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateCurrentLearningEnvelope {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly current: CurrentRepository
  ) {}

  async execute(input: UpdateCurrentLearningEnvelopeInput): Promise<UpdateCurrentLearningEnvelopeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).id) {
      throw new ValidationError("id is required");
    }
    const idValue = (input as any).id;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.current.updateCurrentLearningEnvelope({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateCurrentLearningEnvelopeOutput;
  }
}
