/**
 * GetCreditModel handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getCreditModel } from "@lendora/api-server/domains/models/handlers";
import type { ModelsDDDDependencies } from "@lendora/api-server/domains/models";
import { createVModel as createVModelEntity } from "@lendora/factories/models";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { MODELS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetCreditModel", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelsDDDDependencies>(
      MODELS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createVModelEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetCreditModel, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { modelVersionId: entity.id };

    await getCreditModel(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetCreditModel.execute).toHaveBeenCalledWith(expect.objectContaining({ modelVersionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { modelVersionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetCreditModel, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getCreditModel(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
