/**
 * ApprovePromote Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ApprovePromoteEntity } from "@lendora/core/models/models/index.js";
import { modelsSchemas } from "@lendora/core/models";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mdl";

export function createApprovePromote(overrides: Partial<ApprovePromoteEntity> = {}) {
  const raw = {
    id: overrides.id ?? `mdl_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    role: overrides.role ?? "champion",
    status: overrides.status ?? "candidate",
    tenantId: overrides.tenantId ?? `tnt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return modelsSchemas.ModelVersion.parse(raw);
}

export function approvePromoteBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createApprovePromote(overrides));
}
