/**
 * Claim Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/referrals.openapi.types.js";
import { schemas } from "../schemas/referrals.schemas.js";

/**
 * Entity: ClaimEntity
 * Description: Represents the Claim domain model.
 * Source: schemas.ReferTask
 * Type: Persisted Entity (x-dynamodb)
 */
export const ClaimEntitySchema = schemas.ReferTask;
export type ClaimEntity = components["schemas"]["ReferTask"];
