/**
 * Routes for EarlyWarning
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getEarlyWarning, listEarlyWarnings } from "../handlers/early-warning.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function earlyWarningRoutes(fastify: FastifyInstance) {
  // GET /v1/early-warnings (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/early-warnings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEarlyWarningsDependenciesForRequest();
        await listEarlyWarnings(request, reply, deps);
      });
    }
  );


  // GET /v1/early-warnings/{alertId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/early-warnings/:alertId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEarlyWarningsDependenciesForRequest();
        await getEarlyWarning(request, reply, deps);
      });
    }
  );


}
