/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { acknowledgeRoutes } from "./acknowledge.routes.js";
export { earlyWarningRoutes } from "./early-warning.routes.js";
export { escalateRoutes } from "./escalate.routes.js";
