/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildApplicationsDomainModule } from "./applications/dependencies/applications-ddd.dependencies.js";
export { buildAuditsDomainModule } from "./audits/dependencies/audits-ddd.dependencies.js";
export { buildEarlyWarningsDomainModule } from "./early-warnings/dependencies/early-warnings-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildModelsDomainModule } from "./models/dependencies/models-ddd.dependencies.js";
export { buildPoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export { buildReferralsDomainModule } from "./referrals/dependencies/referrals-ddd.dependencies.js";

// Export all domain dependency types
export type { ApplicationsDomainModule } from "./applications/dependencies/applications-ddd.dependencies.js";
export type { AuditsDomainModule } from "./audits/dependencies/audits-ddd.dependencies.js";
export type { EarlyWarningsDomainModule } from "./early-warnings/dependencies/early-warnings-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { ModelsDomainModule } from "./models/dependencies/models-ddd.dependencies.js";
export type { PoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export type { ReferralsDomainModule } from "./referrals/dependencies/referrals-ddd.dependencies.js";
