/**
 * CreateDecision DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DecideApplicationParams } from "@lendora/core/applications";

export function createCreateDecisionRequest(overrides: Partial<DecideApplicationParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
