/**
 * Routes for Audit
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDecisionAudit, getDecisionAudit, listDecisionAudits } from "../handlers/audit.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function auditRoutes(fastify: FastifyInstance) {
  // POST /v1/audits (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/audits",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await createDecisionAudit(request, reply, deps);
      });
    }
  );


  // GET /v1/audits (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/audits",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await listDecisionAudits(request, reply, deps);
      });
    }
  );


  // GET /v1/audits/{auditId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/audits/:auditId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { auditId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await getDecisionAudit(request, reply, deps);
      });
    }
  );


}
