/**
 * Routes for ByApplication
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getDecisionAuditByApplication } from "../handlers/by-application.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function byApplicationRoutes(fastify: FastifyInstance) {
  // GET /v1/audits/by-application/{applicationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/audits/by-application/:applicationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { applicationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await getDecisionAuditByApplication(request, reply, deps);
      });
    }
  );


}
