/**
 * ByApplicationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ByApplicationRepository Port
 *
 * DDD: Application port for byapplicationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDecisionAuditByApplicationInput, GetDecisionAuditByApplicationOutput } from "../dto/by-application.dto";
export interface ByApplicationRepository {
  getDecisionAuditByApplication(input: GetDecisionAuditByApplicationInput): Promise<GetDecisionAuditByApplicationOutput>;
}

export type { GetDecisionAuditByApplicationInput, GetDecisionAuditByApplicationOutput } from "../dto/by-application.dto";
