/**
 * ExecuteGetDecisionAuditByApplication - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDecisionAuditByApplication Use Case
 *
 * DDD: Application use case for get ByApplication.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDecisionAuditByApplicationInput, GetDecisionAuditByApplicationOutput } from "../dto/by-application.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ByApplicationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDecisionAuditByApplication {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly byApplication: ByApplicationRepository
  ) {}

  async execute(input: GetDecisionAuditByApplicationInput): Promise<GetDecisionAuditByApplicationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).applicationId) {
      throw new ValidationError("applicationId is required");
    }
    const applicationId = (input as any).applicationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.byApplication.getDecisionAuditByApplication({ applicationId: applicationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${applicationId}`);
    }

    return entity as GetDecisionAuditByApplicationOutput;
  }
}
