/**
 * ExecuteListDecisionAudits - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDecisionAudits Use Case
 *
 * DDD: Application use case for list Audit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDecisionAuditsInput, ListDecisionAuditsOutput } from "../dto/audit.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { AuditRepository } from "../ports";

export class ExecuteListDecisionAudits {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly audit: AuditRepository
  ) {}

  async execute(input: ListDecisionAuditsInput): Promise<ListDecisionAuditsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.audit.listDecisionAudits({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDecisionAuditsOutput;
  }
}
