/**
 * ExecuteGetDecisionAudit - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDecisionAudit Use Case
 *
 * DDD: Application use case for get Audit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDecisionAuditInput, GetDecisionAuditOutput } from "../dto/audit.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { AuditRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDecisionAudit {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly audit: AuditRepository
  ) {}

  async execute(input: GetDecisionAuditInput): Promise<GetDecisionAuditOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).auditId) {
      throw new ValidationError("auditId is required");
    }
    const auditId = (input as any).auditId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.audit.getDecisionAudit({ auditId: auditId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${auditId}`);
    }

    return entity as GetDecisionAuditOutput;
  }
}
