/**
 * CurrentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CurrentRepository Port
 *
 * DDD: Application port for currentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCurrentLearningEnvelopeInput, GetCurrentLearningEnvelopeOutput, UpdateCurrentLearningEnvelopeInput, UpdateCurrentLearningEnvelopeOutput } from "../dto/current.dto";
export interface CurrentRepository {
  getCurrentLearningEnvelope(input: GetCurrentLearningEnvelopeInput): Promise<GetCurrentLearningEnvelopeOutput>;
  updateCurrentLearningEnvelope(input: UpdateCurrentLearningEnvelopeInput): Promise<UpdateCurrentLearningEnvelopeOutput>;
}

export type { GetCurrentLearningEnvelopeInput, GetCurrentLearningEnvelopeOutput, UpdateCurrentLearningEnvelopeInput, UpdateCurrentLearningEnvelopeOutput } from "../dto/current.dto";
