/**
 * ProposePromoteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProposePromoteRepository Port
 *
 * DDD: Application port for proposepromoterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ProposePromoteModelInput, ProposePromoteModelOutput } from "../dto/propose-promote.dto";
export interface ProposePromoteRepository {
  proposePromoteModel(input: ProposePromoteModelInput): Promise<ProposePromoteModelOutput>;
}

export type { ProposePromoteModelInput, ProposePromoteModelOutput } from "../dto/propose-promote.dto";
