/**
 * VModelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepository Port
 *
 * DDD: Application port for vmodelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCreditModelInput, GetCreditModelOutput, ListCreditModelsInput, ListCreditModelsOutput, RegisterChallengerModelInput, RegisterChallengerModelOutput } from "../dto/vmodel.dto";
export interface VModelRepository {
  listCreditModels(input: ListCreditModelsInput): Promise<ListCreditModelsOutput>;
  registerChallengerModel(input: RegisterChallengerModelInput): Promise<RegisterChallengerModelOutput>;
  getCreditModel(input: GetCreditModelInput): Promise<GetCreditModelOutput>;
}

export type { GetCreditModelInput, GetCreditModelOutput, ListCreditModelsInput, ListCreditModelsOutput, RegisterChallengerModelInput, RegisterChallengerModelOutput } from "../dto/vmodel.dto";
