/**
 * EarlyWarningRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EarlyWarningRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EarlyWarningRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EarlyWarningRepository,
} from "@lendora/services/early-warnings";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EarlyWarningRepositoryDdb } from "./early-warning-repository.ddb.js";

/**
 * EarlyWarningRepositoryAdapter
 *
 * Implements EarlyWarningRepository port for infrastructure layer.
 */
export class EarlyWarningRepositoryAdapter implements EarlyWarningRepository {
  private readonly ddb: EarlyWarningRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EarlyWarningRepositoryDdb(this.dynamoClient);
  }

  async listEarlyWarnings(input: Parameters<EarlyWarningRepository['listEarlyWarnings']>[0]): Promise<Awaited<ReturnType<EarlyWarningRepository['listEarlyWarnings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEarlyWarnings(input);
  }

  async getEarlyWarning(input: Parameters<EarlyWarningRepository['getEarlyWarning']>[0]): Promise<Awaited<ReturnType<EarlyWarningRepository['getEarlyWarning']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEarlyWarning(input);
  }
}
