/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./acknowledge-repository.ddb.js";
export * from "./early-warning-repository.ddb.js";
export * from "./escalate-repository.ddb.js";
export * from "./acknowledge-repository.adapter.js";
export * from "./early-warning-repository.adapter.js";
export * from "./escalate-repository.adapter.js";
