/**
 * Application Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/applications.openapi.types.js";
import { schemas } from "../schemas/applications.schemas.js";

/**
 * Entity: ApplicationEntity
 * Description: Represents the Application domain model.
 * Source: schemas.Application
 * Type: Persisted Entity (x-dynamodb)
 */
export const ApplicationEntitySchema = schemas.Application;
export type ApplicationEntity = components["schemas"]["Application"];
