/**
 * ProposePromoteModel handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { proposePromoteModel } from "@lendora/api-server/domains/models/handlers";
import type { ModelsDDDDependencies } from "@lendora/api-server/domains/models";
import { createProposePromote as createProposePromoteEntity } from "@lendora/factories/models";
import { createCreateProposePromoteRequest } from "@lendora/factories/models";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { MODELS_USE_CASES } from "../__factories__/use-cases.js";

describe("ProposePromoteModel", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ModelsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ModelsDDDDependencies>(
      MODELS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateProposePromoteRequest();
    const entity = createProposePromoteEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeProposePromoteModel, "execute").mockResolvedValue(useCaseResult);

    await proposePromoteModel(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeProposePromoteModel.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
