/**
 * ExecuteRollbackPolicyPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRollbackPolicyPack Use Case
 *
 * DDD: Application use case for get Rollback.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RollbackPolicyPackInput, RollbackPolicyPackOutput } from "../dto/rollback.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { RollbackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRollbackPolicyPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rollback: RollbackRepository
  ) {}

  async execute(input: RollbackPolicyPackInput): Promise<RollbackPolicyPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyPackId) {
      throw new ValidationError("policyPackId is required");
    }
    const policypackId = (input as any).policyPackId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.rollback.rollbackPolicyPack({ policyPackId: policypackId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policypackId}`);
    }

    return entity as RollbackPolicyPackOutput;
  }
}
