/**
 * ExecuteCreateReasonCode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateReasonCode Use Case
 *
 * DDD: Application use case for create ReasonCode.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateReasonCodeInput, CreateReasonCodeOutput } from "../dto/reason-code.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ReasonCodeRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateReasonCode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reasonCode: ReasonCodeRepository
  ) {}

  async execute(input: CreateReasonCodeInput): Promise<CreateReasonCodeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: code, customerWording, decisionPaths, underwriterWording
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.customerWording) {
      throw new ValidationError("customerWording is required");
    }
    if (!input.underwriterWording) {
      throw new ValidationError("underwriterWording is required");
    }
    if (!input.code) {
      throw new ValidationError("code is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (policies domain)
    const entityId = this.idGenerator.polId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.reasonCode.createReasonCode({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateReasonCodeOutput;
  }
}
