/**
 * ExecuteGetPolicyPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPolicyPack Use Case
 *
 * DDD: Application use case for get Policy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPolicyPackInput, GetPolicyPackOutput } from "../dto/policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { PolicyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPolicyPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policy: PolicyRepository
  ) {}

  async execute(input: GetPolicyPackInput): Promise<GetPolicyPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyPackId) {
      throw new ValidationError("policyPackId is required");
    }
    const policypackId = (input as any).policyPackId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.policy.getPolicyPack({ policyPackId: policypackId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policypackId}`);
    }

    return entity as GetPolicyPackOutput;
  }
}
