/**
 * ExecuteListPolicyPacks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPolicyPacks Use Case
 *
 * DDD: Application use case for list Policy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPolicyPacksInput, ListPolicyPacksOutput } from "../dto/policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { PolicyRepository } from "../ports";

export class ExecuteListPolicyPacks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policy: PolicyRepository
  ) {}

  async execute(input: ListPolicyPacksInput): Promise<ListPolicyPacksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.policy.listPolicyPacks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPolicyPacksOutput;
  }
}
