/**
 * ExecuteUpdateReasonCode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateReasonCode Use Case
 *
 * DDD: Application use case for update ReasonCode.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateReasonCodeInput, UpdateReasonCodeOutput } from "../dto/reason-code.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ReasonCodeRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateReasonCode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reasonCode: ReasonCodeRepository
  ) {}

  async execute(input: UpdateReasonCodeInput): Promise<UpdateReasonCodeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).id) {
      throw new ValidationError("id is required");
    }
    const idValue = (input as any).id;

    // Load existing entity
    const existing = await this.reasonCode.getReasonCode({ id: idValue, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${idValue}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.reasonCode.updateReasonCode({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateReasonCodeOutput;
  }
}
