/**
 * ExecuteListReasonCodes - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListReasonCodes Use Case
 *
 * DDD: Application use case for list ReasonCode.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListReasonCodesInput, ListReasonCodesOutput } from "../dto/reason-code.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ReasonCodeRepository } from "../ports";

export class ExecuteListReasonCodes {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reasonCode: ReasonCodeRepository
  ) {}

  async execute(input: ListReasonCodesInput): Promise<ListReasonCodesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.reasonCode.listReasonCodes({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListReasonCodesOutput;
  }
}
