/**
 * ExecuteCreatePolicyPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePolicyPack Use Case
 *
 * DDD: Application use case for create Policy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePolicyPackInput, CreatePolicyPackOutput } from "../dto/policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { PolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePolicyPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policy: PolicyRepository
  ) {}

  async execute(input: CreatePolicyPackInput): Promise<CreatePolicyPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: excludedSegments, maxAmount, maxDti, productId, productLine, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.productLine) {
      throw new ValidationError("productLine is required");
    }
    if (!input.productId) {
      throw new ValidationError("productId is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (policies domain)
    const entityId = this.idGenerator.polId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.policy.createPolicyPack({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePolicyPackOutput;
  }
}
