/**
 * ExecuteGetReasonCode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetReasonCode Use Case
 *
 * DDD: Application use case for get ReasonCode.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetReasonCodeInput, GetReasonCodeOutput } from "../dto/reason-code.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ReasonCodeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetReasonCode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reasonCode: ReasonCodeRepository
  ) {}

  async execute(input: GetReasonCodeInput): Promise<GetReasonCodeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).reasonCodeId) {
      throw new ValidationError("reasonCodeId is required");
    }
    const reasoncodeId = (input as any).reasonCodeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.reasonCode.getReasonCode({ reasonCodeId: reasoncodeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${reasoncodeId}`);
    }

    return entity as GetReasonCodeOutput;
  }
}
