/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@lendora/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@lendora/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@lendora/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _applications from "./applications/index.js";
import * as _audits from "./audits/index.js";
import * as _earlyWarnings from "./early-warnings/index.js";
import * as _identity from "./identity/index.js";
import * as _models from "./models/index.js";
import * as _policies from "./policies/index.js";
import * as _referrals from "./referrals/index.js";

// Export as namespaces
export const applications = _applications;
export const audits = _audits;
export const earlyWarnings = _earlyWarnings;
export const identity = _identity;
export const models = _models;
export const policies = _policies;
export const referrals = _referrals;
