/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * EarlyWarnings Domain Use Cases
 * 
 * List of all use case names for the early-warnings domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const EARLYWARNINGS_USE_CASES = [
  "executeAcknowledgeEarlyWarning",
  "executeEscalateEarlyWarning",
  "executeGetEarlyWarning",
  "executeListEarlyWarnings"
] as const;
