/**
 * GetReasonCode handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getReasonCode } from "@lendora/api-server/domains/policies/handlers";
import type { PoliciesDDDDependencies } from "@lendora/api-server/domains/policies";
import { createReasonCode as createReasonCodeEntity } from "@lendora/factories/policies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { POLICIES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetReasonCode", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PoliciesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PoliciesDDDDependencies>(
      POLICIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createReasonCodeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetReasonCode, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { reasonCodeId: entity.id };

    await getReasonCode(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetReasonCode.execute).toHaveBeenCalledWith(expect.objectContaining({ reasonCodeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { reasonCodeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetReasonCode, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getReasonCode(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
