/**
 * Handlers for ReasonCode
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PoliciesDomainModule } from "../dependencies/policies-ddd.dependencies.js";
import type { CreateReasonCodeInput, GetReasonCodeInput, ListReasonCodesInput, UpdateReasonCodeInput } from "@lendora/services/policies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/reason-codes
 * Operation: listReasonCodes
 */
export async function listReasonCodes(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListReasonCodesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.reasonCodes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/reason-codes
 * Operation: createReasonCode
 */
export async function createReasonCode(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateReasonCodeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reasonCodes.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/reason-codes/{reasonCodeId}
 * Operation: getReasonCode
 */
export async function getReasonCode(
  request: FastifyRequest<{ Params: { reasonCodeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetReasonCodeInput = {
    reasonCodeId: request.params.reasonCodeId,
  };
  const result = await deps.useCases.reasonCodes.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/reason-codes/{reasonCodeId}
 * Operation: updateReasonCode
 */
export async function updateReasonCode(
  request: FastifyRequest<{ Params: { reasonCodeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateReasonCodeInput = {
    reasonCodeId: request.params.reasonCodeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reasonCodes.update.execute(input);
  return reply.code(200).send(result);
}


