/**
 * Handlers for SubmitApproval
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PoliciesDomainModule } from "../dependencies/policies-ddd.dependencies.js";
import type { SubmitPolicyPackApprovalInput } from "@lendora/services/policies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/policies/{policyPackId}/submit-approval
 * Operation: submitPolicyPackApproval
 */
export async function submitPolicyPackApproval(
  request: FastifyRequest<{ Params: { policyPackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitPolicyPackApprovalInput = {
    policyPackId: request.params.policyPackId,
  };
  const result = await deps.useCases.submitApprovals.create.execute(input);
  return reply.code(200).send(result);
}


