/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the referrals domain.
 * Use these factories in tests to create test data.
 */

export { createClaim } from "./claim/entity/claim.entity.factory.js";
export { createCreateClaimRequest } from "./claim/dto/create-claim.dto.factory.js";
export { createOverride } from "./override/entity/override.entity.factory.js";
export { createReferTask } from "./refer-task/entity/refer-task.entity.factory.js";
