/**
 * EarlyWarnings DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EarlyWarnings Domain Module - Composition root
 *
 * DDD: Composition root for early-warnings domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  EarlyWarningRepositoryAdapter,
  EscalateRepositoryAdapter,
} from "@lendora/adapters/early-warnings";
import { getIdGeneratorService } from "@lendora/adapters";
import type { AdapterDynamoDBClient } from "@lendora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeEarlyWarning,
  ExecuteEscalateEarlyWarning,
  ExecuteGetEarlyWarning,
  ExecuteListEarlyWarnings,
} from "@lendora/services/early-warnings/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  EarlyWarningRepository,
  EscalateRepository,
} from "@lendora/services/early-warnings/ports";

export interface EarlyWarningsDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    earlyWarnings: EarlyWarningRepository;
    escalates: EscalateRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeEarlyWarning;
    };
    earlyWarnings: {
      get: ExecuteGetEarlyWarning;
      list: ExecuteListEarlyWarnings;
    };
    escalates: {
      get: ExecuteEscalateEarlyWarning;
    };
  };
}

export function buildEarlyWarningsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EarlyWarningsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      earlyWarnings?: EarlyWarningRepository;
      escalates?: EscalateRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.earlyWarnings = new EarlyWarningRepositoryAdapter(dynamoClient);
    obj.escalates = new EscalateRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      earlyWarnings: obj.earlyWarnings!,
      escalates: obj.escalates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeEarlyWarning(executionContext, idGenerator, repos.acknowledges),
    },
    earlyWarnings: {
      get: new ExecuteGetEarlyWarning(executionContext, idGenerator, repos.earlyWarnings),
      list: new ExecuteListEarlyWarnings(executionContext, idGenerator, repos.earlyWarnings),
    },
    escalates: {
      get: new ExecuteEscalateEarlyWarning(executionContext, idGenerator, repos.escalates),
    },
  };
  return { repos, useCases: useCases as EarlyWarningsDomainModule["useCases"] };
}
