/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Policies Domain Use Cases
 * 
 * List of all use case names for the policies domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const POLICIES_USE_CASES = [
  "executeApprovePolicyPack",
  "executeCreatePolicyPack",
  "executeCreateReasonCode",
  "executeGetPolicyPack",
  "executeGetReasonCode",
  "executeListPolicyPacks",
  "executeListReasonCodes",
  "executePublishReasonCode",
  "executeRollbackPolicyPack",
  "executeSimulatePolicyVeto",
  "executeSubmitPolicyPackApproval",
  "executeUpdatePolicyPack",
  "executeUpdateReasonCode"
] as const;
