/**
 * GetDecisionAudit handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDecisionAudit } from "@lendora/api-server/domains/audits/handlers";
import type { AuditsDDDDependencies } from "@lendora/api-server/domains/audits";
import { createAudit as createAuditEntity } from "@lendora/factories/audits";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { AUDITS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDecisionAudit", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditsDDDDependencies>(
      AUDITS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createAuditEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDecisionAudit, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { auditId: entity.id };

    await getDecisionAudit(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDecisionAudit.execute).toHaveBeenCalledWith(expect.objectContaining({ auditId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { auditId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDecisionAudit, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDecisionAudit(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
