/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { currentRoutes } from "./current.routes.js";
export { approvePromoteRoutes } from "./approve-promote.routes.js";
export { proposePromoteRoutes } from "./propose-promote.routes.js";
export { vModelRoutes } from "./vmodel.routes.js";
