/**
 * Routes for ProposePromote
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { proposePromoteModel } from "../handlers/propose-promote.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function proposePromoteRoutes(fastify: FastifyInstance) {
  // POST /v1/models/{modelVersionId}/propose-promote (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/models/:modelVersionId/propose-promote",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getModelsDependenciesForRequest();
        await proposePromoteModel(request, reply, deps);
      });
    }
  );


}
