/**
 * Routes for VModel
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCreditModel, listCreditModels, registerChallengerModel } from "../handlers/vmodel.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function vModelRoutes(fastify: FastifyInstance) {
  // GET /v1/models (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/models",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getModelsDependenciesForRequest();
        await listCreditModels(request, reply, deps);
      });
    }
  );


  // POST /v1/models (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/models",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getModelsDependenciesForRequest();
        await registerChallengerModel(request, reply, deps);
      });
    }
  );


  // GET /v1/models/{modelVersionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/models/:modelVersionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getModelsDependenciesForRequest();
        await getCreditModel(request, reply, deps);
      });
    }
  );


}
