/**
 * GetEarlyWarning handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getEarlyWarning } from "@lendora/api-server/domains/early-warnings/handlers";
import type { EarlyWarningsDDDDependencies } from "@lendora/api-server/domains/early-warnings";
import { createEarlyWarning as createEarlyWarningEntity } from "@lendora/factories/early-warnings";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@lendora/tests/shared";
import { EARLYWARNINGS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetEarlyWarning", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EarlyWarningsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EarlyWarningsDDDDependencies>(
      EARLYWARNINGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createEarlyWarningEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetEarlyWarning, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { alertId: entity.id };

    await getEarlyWarning(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetEarlyWarning.execute).toHaveBeenCalledWith(expect.objectContaining({ alertId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { alertId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetEarlyWarning, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getEarlyWarning(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
