/**
 * ExecuteListReferTasks - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListReferTasks Use Case
 *
 * DDD: Application use case for list ReferTask.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListReferTasksInput, ListReferTasksOutput } from "../dto/refer-task.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { ReferTaskRepository } from "../ports";

export class ExecuteListReferTasks {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly referTask: ReferTaskRepository
  ) {}

  async execute(input: ListReferTasksInput): Promise<ListReferTasksOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.refId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.referTask.listReferTasks({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListReferTasksOutput;
  }
}
