/**
 * ExecuteCreateOverride - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateOverride Use Case
 *
 * DDD: Application use case for create Override.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateOverrideInput, CreateOverrideOutput } from "../dto/override.dto";
import type { ExecutionContextService, IdGeneratorService } from "@lendora/services/_shared/index.js";
import type { OverrideRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateOverride {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly override: OverrideRepository
  ) {}

  async execute(input: CreateOverrideInput): Promise<CreateOverrideOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.refId();

    // All field names extracted from OpenAPI spec: finalOutcome, justification
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.justification) {
      throw new ValidationError("justification is required");
    }
    if (!input.finalOutcome) {
      throw new ValidationError("finalOutcome is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (referrals domain)
    const entityId = this.idGenerator.refId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.override.createOverride({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateOverrideOutput;
  }
}
