/**
 * ListApplication DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListApplicationsParams } from "@lendora/core/applications";

export function createListApplicationRequest(overrides: Partial<ListApplicationsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
