/**
 * Escalate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/early-warnings.openapi.types.js";
import { schemas } from "../schemas/early-warnings.schemas.js";

/**
 * Entity: EscalateEntity
 * Description: Represents the Escalate domain model.
 * Source: schemas.EarlyWarningAlert
 * Type: Persisted Entity (x-dynamodb)
 */
export const EscalateEntitySchema = schemas.EarlyWarningAlert;
export type EscalateEntity = components["schemas"]["EarlyWarningAlert"];
