/**
 * ReferTaskRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReferTaskRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReferTaskRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReferTaskRepository,
} from "@lendora/services/referrals";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReferTaskRepositoryDdb } from "./refer-task-repository.ddb.js";

/**
 * ReferTaskRepositoryAdapter
 *
 * Implements ReferTaskRepository port for infrastructure layer.
 */
export class ReferTaskRepositoryAdapter implements ReferTaskRepository {
  private readonly ddb: ReferTaskRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReferTaskRepositoryDdb(this.dynamoClient);
  }

  async listReferTasks(input: Parameters<ReferTaskRepository['listReferTasks']>[0]): Promise<Awaited<ReturnType<ReferTaskRepository['listReferTasks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReferTasks(input);
  }

  async getReferTask(input: Parameters<ReferTaskRepository['getReferTask']>[0]): Promise<Awaited<ReturnType<ReferTaskRepository['getReferTask']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReferTask(input);
  }
}
