/**
 * FeaturePackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: applications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FeaturePackRepository Port
 *
 * DDD: Application port for featurepackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetApplicationFeaturePackInput, GetApplicationFeaturePackOutput, UpsertApplicationFeaturePackInput, UpsertApplicationFeaturePackOutput } from "../dto/feature-pack.dto";
export interface FeaturePackRepository {
  getApplicationFeaturePack(input: GetApplicationFeaturePackInput): Promise<GetApplicationFeaturePackOutput>;
  upsertApplicationFeaturePack(input: UpsertApplicationFeaturePackInput): Promise<UpsertApplicationFeaturePackOutput>;
}

export type { GetApplicationFeaturePackInput, GetApplicationFeaturePackOutput, UpsertApplicationFeaturePackInput, UpsertApplicationFeaturePackOutput } from "../dto/feature-pack.dto";
