/**
 * Claim DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Claim DTOs
 *
 * DDD: Application DTOs for Claim use cases.
 */

import type { ClaimReferTaskParams } from "@lendora/core/referrals/types";

export type ClaimReferTaskInput = ClaimReferTaskParams;

export type ClaimReferTaskOutput = {};
