/**
 * ReferTask DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReferTask DTOs
 *
 * DDD: Application DTOs for ReferTask use cases.
 */

import type { GetReferTaskParams, ListReferTasksParams } from "@lendora/core/referrals/types";

export type ListReferTasksInput = ListReferTasksParams;

export type GetReferTaskInput = GetReferTaskParams;

export type ListReferTasksOutput = {};

export type GetReferTaskOutput = {};
