/**
 * CreateEscalate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: early-warnings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { EscalateEarlyWarningParams } from "@lendora/core/early-warnings";

export function createCreateEscalateRequest(overrides: Partial<EscalateEarlyWarningParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
