/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { claimRoutes } from "./claim.routes.js";
export { overrideRoutes } from "./override.routes.js";
export { referTaskRoutes } from "./refer-task.routes.js";
