/**
 * Handlers for Current
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelsDomainModule } from "../dependencies/models-ddd.dependencies.js";
import type { GetCurrentLearningEnvelopeInput, UpdateCurrentLearningEnvelopeInput } from "@lendora/services/models";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/learning-envelopes/current
 * Operation: getCurrentLearningEnvelope
 */
export async function getCurrentLearningEnvelope(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCurrentLearningEnvelopeInput = {};
  const result = await deps.useCases.currents.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/learning-envelopes/current
 * Operation: updateCurrentLearningEnvelope
 */
export async function updateCurrentLearningEnvelope(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateCurrentLearningEnvelopeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.currents.update.execute(input);
  return reply.code(200).send(result);
}


