/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-promote.handlers.js";
export * from "./current.handlers.js";
export * from "./propose-promote.handlers.js";
export * from "./vmodel.handlers.js";
