/**
 * Handlers for VModel
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelsDomainModule } from "../dependencies/models-ddd.dependencies.js";
import type { GetCreditModelInput, ListCreditModelsInput, RegisterChallengerModelInput } from "@lendora/services/models";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/models
 * Operation: listCreditModels
 */
export async function listCreditModels(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], role?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCreditModelsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.vModels.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/models
 * Operation: registerChallengerModel
 */
export async function registerChallengerModel(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterChallengerModelInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.vModels.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/models/{modelVersionId}
 * Operation: getCreditModel
 */
export async function getCreditModel(
  request: FastifyRequest<{ Params: { modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetCreditModelInput = {
    modelVersionId: request.params.modelVersionId,
  };
  const result = await deps.useCases.vModels.get.execute(input);
  return reply.code(200).send(result);
}


