/**
 * GetReferTask DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: referrals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetReferTaskParams } from "@lendora/core/referrals";

export function createGetReferTaskRequest(overrides: Partial<GetReferTaskParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
