/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Models Domain Use Cases
 * 
 * List of all use case names for the models domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const MODELS_USE_CASES = [
  "executeApprovePromoteModel",
  "executeGetCreditModel",
  "executeGetCurrentLearningEnvelope",
  "executeListCreditModels",
  "executeProposePromoteModel",
  "executeRegisterChallengerModel",
  "executeUpdateCurrentLearningEnvelope"
] as const;
